/*BY SUBMITTING THIS FILE TO CARMEN, I CERTIFY THAT I HAVE PERFORMED ALL OF
THE WORK TO CREATE THIS FILE AND/OR DETERMINE THE ANSWERS FOUND WITHIN
THIS FILE MYSELF WITH NO ASSISTANCE FROM ANY PERSON (OTHER THAN THE
INSTRUCTOR OR GRADERS OF THIS COURSE) AND I HAVE STRICTLY ADHERED TO THE
TENURES OF THE OHIO STATE UNIVERSITY’S ACADEMIC INTEGRITY POLICY */

#include <stdio.h>

long sum( long a [], int count);

int main(int argc, char **argv){
	long a [] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
	printf("Main ..... call sum\n");
	sum(a, 10);
	printf("\ndone!\n");
	return 0;
}

